---
dependency:
  name: galaxy
driver:
  name: docker
# lint: ansible-lint
platforms:
  - name: el-instance
    groups: 
      - elasticsearch
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: centos7
    groups: 
      - kibana
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  # - name: centos8
  #   groups: 
  #     - kibana
  #   image: docker.io/pycontribs/centos:8
  #   pre_build_image: true
  # - name: ubuntu
  #   groups: 
  #     - kibana
  #   image: docker.io/pycontribs/ubuntu:latest
  #   pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
