---
- src: git@github.com:netology-code/mnt-homeworks-ansible.git
  scm: git
  version: "2.0.0"
  name: elasticsearch-role

- src: git@github.com:maxship/kibana-role.git
  scm: git
  version: "1.0.0"
  name: kibana-role

- src: git@github.com:maxship/filebeat-role.git
  scm: git
  version: "1.0.0"
  name: filebeat-role
