---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # инстанс с эластиком 
  - name: el-instance
    groups: 
      - elasticsearch
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
  # инстанс с кибаной
  - name: kibana-instance
    groups: 
      - kibana
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
  # платформы для тестирования роли
  - name: centos7
    groups: 
      - filebeat
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
  - name: centos8
    groups: 
      - filebeat
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true  
  - name: ubuntu
    groups: 
      - filebeat
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
