---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: elastic
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
