---
- name: Enable Filebeat service
  become: true
  service:
    name: filebeat
    state: started
    enabled: yes

- name: Configure Filebeat
  become: true
  template:
    src: filebeat.yml.j2
    mode: 0644
    dest: /etc/filebeat/filebeat.yml
  notify: restart Filebeat

- name: Set Filebeat modules
  become: true
  command:
    cmd: filebeat modules enable system
    chdir: /usr/share/filebeat/bin
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is already enabled'

