---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
- name: el-instance
  groups: 
  - elasticsearch
  image: docker.io/pycontribs/centos:7
  pre_build_image: true
  command: /usr/sbin/init
  privileged: true
- name: kibana-instance
  groups: 
    - kibana
  image: docker.io/pycontribs/centos:7
  pre_build_image: true
  command: /usr/sbin/init
  privileged: true 
- name: centos7
  groups: 
    - filebeat
  image: docker.io/pycontribs/centos:7
  pre_build_image: true
  command: /usr/sbin/init
  privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
