---
- name: Elastic
  hosts: elasticsearch
  tasks:
    - name: "Include elasticsearch-role"
      include_role:
        name: "elasticsearch-role"

- name: Kibana
  hosts: kibana
  tasks:
    - name: "Include kibana-role"
      include_role:
        name: "kibana-role"
