---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
- name: el-instance
  groups: 
    - elasticsearch
  image: docker.io/pycontribs/centos:7
  pre_build_image: true
- name: kb-instance
  groups: 
    - kibana
  image: docker.io/pycontribs/centos:7
  pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
